### ISSUE TITLE
Image always zoomed in

### ISSUE THREAD

**Issue by m-i-n-a-r** [RanfiCD/diagonal_scrollview#6]
I'm using diagonal scrollview to show different images of a map. The images have different sizes and aspect ratios, and the common issue (but maybe i'm missing something) is that even if i set different values of maximum scale, the image is always super-zoomed in when i open the app, and i have to manually zoom out. The desired behavior, in my case, is having the image zoomed out to match the width or the height with the container width or height, having the possibility to zoom in and scroll in every direction. Thanks in advance!

**Comment by RanfiCD** [comment]
Hello!

What parameters are you passing to DiagonalScrollView? Could you give a code example that reproduces your case?

Thanks!

**Comment by m-i-n-a-r** [comment]
Sorry for being late! Anyway, i guess that the default zoom level can be controlled using the controller property. As a Flutter newbie, i didn't know that. A "default scale" property could surely help, but that's not a real issue!
